name: spherical-steering
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.2
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - dbus=1.16.2
  - einops=0.8.1
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - git=2.52.0
  - glslang=16.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - intel-gmmlib=22.8.2
  - intel-media-driver=25.3.4
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.26.0
  - libabseil=20250512.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libblas=3.9.0
  - libcap=2.77
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsentencepiece=0.2.1
  - libsndfile=1.2.2
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.2
  - libtiff=4.7.1
  - libudev1=258.2
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.41.2
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pandas=2.3.3
  - pango=1.56.4
  - pcre2=10.46
  - perl=5.32.1
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - sdl2=2.32.56
  - sdl3=3.2.26
  - sentencepiece=0.2.1
  - sentencepiece-python=0.2.1
  - sentencepiece-spm=0.2.1
  - setuptools=80.9.0
  - shaderc=2025.4
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.3
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - baukit==0.0.1
      - blake3==1.0.8
      - cachetools==6.2.2
      - cbor2==5.7.1
      - click==8.2.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==4.4.1
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.1
      - fastapi==0.121.3
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.5.1
      - fastar==0.7.0
      - fastrlock==0.8.3
      - flashinfer-python==0.5.2
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - interegular==0.3.3
      - jiter==0.12.0
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - model-hosting-container-standards==0.1.9
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - ninja==1.13.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.0
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.8.1
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - packaging==25.0
      - partial-json-parser==0.2.1.1.post7
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pyzmq==27.1.0
      - ray==2.52.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rich==14.2.0
      - rich-toolkit==0.16.0
      - rignore==0.7.6
      - rpds-py==0.29.0
      - safetensors==0.7.0
      - sentry-sdk==2.46.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.50.0
      - supervisor==4.3.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.1
      - triton==3.5.0
      - typer==0.20.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.2
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
